### ISSUE TITLE
Flyweight primitive Iterator: disappointing performance

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#20]
I have merged the flyweight primitive Iterator by @bobymicroby in the main branch.

The performance results are disappointing:

      $ mvn -Dtest=TestBenchmarkIterator test
      Running org.roaringbitmap.TestBenchmarkIterator
      TestBenchmarkIterator.testFlyweight: [measured 50000 out of 50003 rounds, threads: 1 (sequential)]
       round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 0.68, time.warmup: 0.00, time.bench: 0.68
      TestBenchmarkIterator.testStandard: [measured 50000 out of 50003 rounds, threads: 1 (sequential)]
       round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 6, GC.time: 0.01, time.total: 0.42, time.warmup: 0.00, time.bench: 0.42
      Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.816 sec - in org.roaringbitmap.TestBenchmarkIterator

See 
https://github.com/lemire/RoaringBitmap/blob/master/src/test/java/org/roaringbitmap/TestBenchmarkIterator.java

Should we keep these new iterators?

**Comment by bobymicroby** [comment]
Most benchmarking tools beside JMH tend to give very faulty and misleading results. I have observed better throughput both in the micro-benchmark and in real scenario. GC will always stab you in the back when you generate many Iterator objects ( I am not quite sure that you achieve this in your benchmark ) .

I really would suggest that you try to do a transition to JMH

Shorts slides about what pitfalls are JMH helping to avoid : http://www.oracle.com/technetwork/java/jvmls2013ship-2014087.pdf

This fine collection of resources about JMH http://psy-lob-saw.blogspot.com/p/jmh-related-posts.html can help as well.

**Comment by bobymicroby** [comment]
Benchmarking is really hard thing. There is a big chance that I am doing it wrong. But JMH tend to minimize the risks. I attaching a little recoding of the heap usage of both variants under stress.

Standard Iterator 1 minute under stress:

![image](https://cloud.githubusercontent.com/assets/927575/6643764/a120ab44-c9b7-11e4-95cc-9354eba4b70e.png)



Flyweight Iterator 1 minute under stress:

![image](https://cloud.githubusercontent.com/assets/927575/6643769/ab0e730c-c9b7-11e4-8c4c-ba78b4030a7e.png)

**Comment by lemire** [comment]
@bobymicroby 

I am closing this issue as I have refined the benchmark and I get more reliable numbers.

        $ mvn -Dtest=TestBenchmarkIterator test
        TestBenchmarkIterator.testFlyweight: [measured 10 out of 15 rounds, threads: 1 (sequential)]
 round: 0.08 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 1.19, time.warmup: 0.43, time.bench: 0.77
        TestBenchmarkIterator.testStandard: [measured 10 out of 20 rounds, threads: 1 (sequential)]
 round: 0.13 [+- 0.02], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 3, GC.time: 0.15, time.total: 2.66, time.warmup: 1.38, time.bench: 1.29

These tests do indicate that iterations can be accelerated considerably by avoiding the creation of so many temporary objects. I think that my previous numbers were probably garbage.

Note that it should be possible to achieve much the goals you set forth within the main code.

I would love to replace our junitbenchmarks with something better, maybe using JMH. 

If you could contribute JMH benchmarks, that would be great... As for myself, I tried to replace the junitbenchmarks with something based on JMH, but after several hours, I gave up.

Ideally, I would want something where you can just enter a command line argument and get a text output that you can share.

**Comment by bobymicroby** [comment]
@lemire  Hello again. Adopting JMH is really a right thing to do. I will try to setup the benchmarking infrastructure when I can squeeze few cycles out of myself. 
B.
