### ISSUE TITLE
Implement galloping intersections at the container-array level

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#23]
@gssiyankai Submitted a PR 

https://github.com/lemire/RoaringBitmap/pull/22

where he proposes to accelerate intersections (AND) between bitmaps by computing a two-way galloping  intersection between the 16-bit keys at the upper level of the data structure. I merged his PR for further study.

This issue is meant to document this proposal further.

Reference (benchmark code): https://github.com/lemire/RoaringBitmap/tree/master/jmh

**Comment by lemire** [comment]
After fixing a few issues, the results are conclusive. In extreme cases, we see a clear benefit (huge performance boost) and in other cases we see no performance degradation.


        o.r.a.n.bestcase.RoaringBitmapBenchmark.and              avgt    5    71.979 ±   1.822  us/op
        o.r.a.n.bestcase.RoaringBitmapBenchmark.newand           avgt    5     1.438 ±   0.005  us/op

        o.r.a.n.bestcase.RoaringBitmapBenchmark.inplace_and      avgt    5  4711.711 ± 201.581  us/op
        o.r.a.n.bestcase.RoaringBitmapBenchmark.inplace_newand   avgt    5   206.450 ±   0.815  us/op
        o.r.a.n.bestcase.RoaringBitmapBenchmark.justclone        avgt    5   223.219 ±   1.600  us/op





        o.r.a.n.identical.RoaringBitmapBenchmark.and             avgt    5   315.029 ±   1.965  us/op
        o.r.a.n.identical.RoaringBitmapBenchmark.newand          avgt    5   319.878 ±   0.950  us/op

        o.r.a.n.identical.RoaringBitmapBenchmark.inplace_and     avgt    5   271.287 ±   1.930  us/op
        o.r.a.n.identical.RoaringBitmapBenchmark.inplace_newand  avgt    5   265.371 ±   1.531  us/op
        o.r.a.n.identical.RoaringBitmapBenchmark.justclone       avgt    5   192.239 ±   0.913  us/op





        o.r.a.n.worstcase.RoaringBitmapBenchmark.and             avgt    5   229.724 ±   0.507  us/op
        o.r.a.n.worstcase.RoaringBitmapBenchmark.newand          avgt    5   215.049 ±   0.287  us/op
        
        o.r.a.n.worstcase.RoaringBitmapBenchmark.inplace_and     avgt    5  4646.484 ±  44.808  us/op
        o.r.a.n.worstcase.RoaringBitmapBenchmark.inplace_newand  avgt    5   258.431 ±   1.006  us/op
        o.r.a.n.worstcase.RoaringBitmapBenchmark.justclone       avgt    5   192.436 ±   1.133  us/op

**Comment by lemire** [comment]
Remaining issues to resolve:

1. We need to replace "newand" with "and" throughout.
2. The same optimization should be applied to andNot methods throughout.
3. The same optimization should be applied to the classes in org.roaringbitmap.buffer.

Re-assigning to @gssiyankai to see what he can do.

**Comment by gssiyankai** [comment]
Remaining issues have been fixed in master branch.
Closing.
