### ISSUE TITLE
Port all benchmarks to jmh

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#24]
@bobymicroby Pointed out that JMH benchmarking should be the way to go (in PR https://github.com/lemire/RoaringBitmap/pull/19 )

@gssiyankai  contributed an initial set of JMH benchmarks in PR https://github.com/lemire/RoaringBitmap/issues/23

I think we should go all JMH now and port the existing junit benchmarks (e.g. see https://github.com/lemire/RoaringBitmap/tree/master/src/test/java/org/roaringbitmap ) to JMH.

This would have a few benefits:

* Hopefully improve the quality of the benchmarks,
* Separate testing code from benchmarking code, thus making the builds faster.

Temporarily assigning to @gssiyankai feel free to reassign to me.

**Comment by bobymicroby** [comment]
Hello @lemire  . I have not forgotten :), I will try to include mine benchmarks/rewrite others as soon as I am free from my other tasks.

**Comment by lemire** [comment]
@bobymicroby 

That would be appreciated. Thanks to @gssiyankai, we have a jmh directory with a pom.xml file and everything... so the bar to adding new JMH benchmarks is much lower than it was a few days ago.

**Comment by bobymicroby** [comment]
@lemire I have ported the benchmarks as-is in  PR #25

**Comment by lemire** [comment]
@bobymicroby  I have removed the old-style junit benchmarks.

I think that this solves this issue entirely. I am closing it off.

Here is the results of our benchmarks at this time:

            Benchmark                                                            Mode  Cnt     Score     Error  Units
            BasicBenchmark.bigunion_immutable                                   thrpt    5     1.091 ±   0.002  ops/s
            BasicBenchmark.bigunion_mutable                                     thrpt    5     2.054 ±   0.009  ops/s
            BasicBenchmark.bigunion_standard                                    thrpt    5     2.145 ±   0.015  ops/s
            BasicBenchmark.cardinality_immutable                                thrpt    5   387.537 ±   1.138  ops/s
            BasicBenchmark.cardinality_mutable                                  thrpt    5   248.858 ±  10.831  ops/s
            BasicBenchmark.cardinality_standard                                 thrpt    5   248.357 ±  11.390  ops/s
            BasicBenchmark.createBitmapOrdered_mutable                          thrpt    5   880.412 ±   2.871  ops/s
            BasicBenchmark.createBitmapOrdered_standard                         thrpt    5  1078.183 ±   3.068  ops/s
            BasicBenchmark.createBitmapUnordered_mutable                        thrpt    5   186.701 ±   0.850  ops/s
            BasicBenchmark.createBitmapUnordered_standard                       thrpt    5   209.941 ±   0.519  ops/s
            BasicBenchmark.toarray_immutable                                    thrpt    5     8.682 ±   0.137  ops/s
            BasicBenchmark.toarray_mutable                                      thrpt    5    11.932 ±   0.332  ops/s
            BasicBenchmark.toarray_standard                                     thrpt    5    12.114 ±   0.148  ops/s
            iteration.IteratorsBenchmark.testFlyweight_a                        thrpt    5  1514.026 ±   1.371  ops/s
            iteration.IteratorsBenchmark.testFlyweight_b                        thrpt    5     7.612 ±   0.002  ops/s
            iteration.IteratorsBenchmark.testStandard_a                         thrpt    5  1294.660 ± 110.984  ops/s
            iteration.IteratorsBenchmark.testStandard_b                         thrpt    5    10.956 ±   0.290  ops/s
            aggregation.newand.bestcase.RoaringBitmapBenchmark.and               avgt    5    71.971 ±   1.874  us/op
            aggregation.newand.bestcase.RoaringBitmapBenchmark.inplace_and       avgt    5  4746.211 ±  90.552  us/op
            aggregation.newand.bestcase.RoaringBitmapBenchmark.inplace_newand    avgt    5   206.603 ±   0.903  us/op
            aggregation.newand.bestcase.RoaringBitmapBenchmark.justclone         avgt    5   223.070 ±   0.976  us/op
            aggregation.newand.bestcase.RoaringBitmapBenchmark.newand            avgt    5     1.435 ±   0.004  us/op
            aggregation.newand.identical.RoaringBitmapBenchmark.and              avgt    5   322.480 ±   1.952  us/op
            aggregation.newand.identical.RoaringBitmapBenchmark.inplace_and      avgt    5   271.152 ±   1.896  us/op
            aggregation.newand.identical.RoaringBitmapBenchmark.inplace_newand   avgt    5   265.405 ±   1.057  us/op
            aggregation.newand.identical.RoaringBitmapBenchmark.justclone        avgt    5   221.979 ±   0.673  us/op
            aggregation.newand.identical.RoaringBitmapBenchmark.newand           avgt    5   320.131 ±   1.509  us/op
            aggregation.newand.worstcase.RoaringBitmapBenchmark.and              avgt    5   229.073 ±   0.458  us/op
            aggregation.newand.worstcase.RoaringBitmapBenchmark.inplace_and      avgt    5  4644.705 ±  38.715  us/op
            aggregation.newand.worstcase.RoaringBitmapBenchmark.inplace_newand   avgt    5   267.817 ±   1.433  us/op
            aggregation.newand.worstcase.RoaringBitmapBenchmark.justclone        avgt    5   222.629 ±   0.383  us/op
            aggregation.newand.worstcase.RoaringBitmapBenchmark.newand           avgt    5   215.290 ±   0.343  us/op
