### ISSUE TITLE
Reduce memory usage by getting rid of the internal Element classes

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#31]
We store containers within Element objects. This adds memory overhead (24 bytes per instance).

It would be more economical to store the keys in an array and the containers in another array, thus compacting the whole data structure.

**Comment by bobymicroby** [comment]
:+1:

**Comment by gssiyankai** [comment]
I submitted a fix in the runcontainer branch 31dc433533ddb777fb58cad739b28de88207c4e1
It will be merged in the master branch soon.

**Comment by lemire** [comment]
The issue should now be resolved as of the release of the 0.5.0 version.
