### ISSUE TITLE
Feature Request: Set operations (does_it_intersects, or_cardinality, and_cardinality...)

### ISSUE THREAD

**Issue by llogiq** [lemire/RoaringBitmap#36]
It should be possible to implement fairly fast set operations like `intersects(RoaringBitmap)` (a method that even `BitSet` has) and `containsAll(RoaringBitmap)` (a method that `BitSet` lacks, but could be quite handy in some cases).

Also a fast method to *count* the bits of intersections/unions might be useful (I'm using RoaringBitmaps for a Jaccard Index, where both is needed – so a method that does both fast would be even more awesome). Granted, the latter is really specific, so I have no hard feelings if it doesn't get implemented.

Perhaps providing a method `Stream<Pair> pairStream(RoaringBitmap, RoaringBitmap)` where each `Pair` has an index + two longs with the bits wherever at least one of the bitmaps has bits could be used to solve all of the above issues in a generic way?

**Comment by lemire** [comment]
> It should be possible to implement fairly fast set operations like intersects(RoaringBitmap) (a method that even BitSet has) 

You are correct. This should be added.

> and containsAll(RoaringBitmap) (a method that BitSet lacks, but could be quite handy in some cases)

This could be added for convenience, but it can be implemented as ```(RoaringBitmap.xor(first,second).getCardinality() == 0)```.

> Also a fast method to count the bits of intersections/unions might be useful

Agreed. This should be added as well.

> Perhaps providing a method Stream<Pair> pairStream(RoaringBitmap, RoaringBitmap) where each Pair has an index + two longs with the bits wherever at least one of the bitmaps has bits could be used to solve all of the above issues in a generic way?

I do not understand this proposal. Can you give an example?

**Comment by llogiq** [comment]
> `(RoaringBitmap.xor(first,second).getCardinality() == 0)`

This requires potentially a good amount of memory, whereas a direct method should be fairly frugal in that regard. I'm unsure how this would affect performance.

> I do not understand this proposal. Can you give an example?

Yea, I was thinking in terms of BitSets. It doesn't make sense anywhere else. Disregard this one.

**Comment by lemire** [comment]
By the way... forget my xor thing, it won't do the job.

You need andNot...

**Comment by lemire** [comment]
This should probably be a priority for future work.

c.c. @llogiq  @gpunti @gssiyankai @rorygraves

**Comment by lemire** [comment]
@llogiq 

Version 0.5.6 implements "intersects" which is the "does_it_intersects" part of this issue.

We still need to add or_cardinality and and_cardinality.

**Comment by llogiq** [comment]
@lemire Thank you!

**Comment by lemire** [comment]
This has been mostly resolved with version 0.5.12. The performance could still be improved, but the basic support is there (thanks to @JervenBolleman ).

So I am closing for now. If people want to help improve the performance further, get in touch with me, there are opportunities.
