### ISSUE TITLE
Reduce temporary object allocation

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#40]
RoaringBitmap creates lots of temporary objects in the course of running even the smallest bit of code. This puts a lot of stress on the garbage collector and degrades real-world performance.

There is need for a good benchmark that would determine where the problems are. For example, there are indications that the call to "asShortBuffer" followed by "slice" create unnecessary objects.

Possibly relevant benchmarks:

          $ cd RoaringBitmap
          $ git pull
          $ cd jmh
          $ ./run.sh needwork

**Comment by gssiyankai** [comment]
@lemire 

Now that we've released version 0.5.2 with significant improvements in memory usage and execution time, do you think we can close this issue ?

**Comment by lemire** [comment]
@gssiyankai I would think so.
