### ISSUE TITLE
For run containers: implement in-place flips (inot) and optimize not operators

### ISSUE THREAD

**Issue by lemire** [lemire/RoaringBitmap#45]
Currently, run containers do not support in-place "inot" operations. Moreover, even their not operators might produce containers than are suboptimal storage-wise.

https://github.com/lemire/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/RunContainer.java#L632-L637

It seems like this is easily fixed and would be useful for applications that rely heavily on complements/flipping.

**Comment by lemire** [comment]
Version 0.5.6 checks whether flipped run containers need to be converted.

cc: @owenkaser

**Comment by owenkaser** [comment]
Okay, as noted, I have a bunch of things that I am working on wrt this.  I
was just going back to work on this.

**Comment by lemire** [comment]
@owenkaser 

Ok. The change in 0.5.6 is just a single extra line that should add safety, and can be trivially reverted. It is maybe less nice that I removed what I considered to be broken tests, but they can be put back.

Sorry if this change interfered with your ongoing work... this was a change I made "en passant" while adding "intersects" functions.

**Comment by owenkaser** [comment]
You may need to help me out with git on this.  I worked all day yesterday
on these issues (fixing the unit tests that you discarded,  writing a
proper in place inot  (discarded my first attempt, after it was heading
into case analysis hell, and now am working on an in-place version based on
your "not" code).  Anyway, I did not make a branch (not sure whether I can
make a remote branch, or whether only you can) and have a lot of work not
committed (until it gets closer to working).

I a) am worried about how git will handle the conflicts  b) don't want to
commit code to the main line until it is pretty heavily tested.   And I
don't know if I will get my code to that state in the next couple of
hours.  The fact that I don't properly understand git in tricky cases, and
the fact that the repository is used by other people,  have me worried
about doing anything.

**Comment by lemire** [comment]
Good day,

It is entirely reasonable to push your changes to a branch. You don't lose
 uncommited changes when moving to another branch. So you should just be
able to do this:

git checkout -b owensnot

git push -u origin owensnot

(Of course, if I were you, I would backup all my changes "just in case".
Git is known to do weird stuff.)

Alternatively, you can fork the main project...  (Go to
https://github.com/lemire/RoaringBitmap and "click" fork) Then with "git
clone git@github.com:owenkaser/RoaringBitmap.git" (or something like this
command), grab a copy of your fork, do all the changes you want to make
*then* issue a pull request.

The fork followed by a PR works well if you are uneasy about make changes
directly in the main code.


BTW I did not mean to irritate you with my change. It is something I did
without hardly thinking about it. It felt like patching up a hole, at least
temporarily.

Cheers!

- Daniel

**Comment by lemire** [comment]
Of relevance to this issue is @owenkaser  commit: https://github.com/lemire/RoaringBitmap/commit/145bbc3365e6b46e785827a9649248faf2376898

**Comment by lemire** [comment]
Merged @owenkaser's branch regarding this issue in master. Ported his inot to MappeableRunContainer.

I think that this resolves this issue. I am closing.
