### ISSUE TITLE
Accept ImmutableBitmapDataProvider in aggregation operations (or/and)

### ISSUE THREAD

**Issue by benjamin84** [lemire/RoaringBitmap#59]
The signature of the aggregation methods add(), and(), andNot), etc. don't accept ImmutableBitmapDataProvider as source.

**Comment by lemire** [comment]
I do not think it is doable given that we want to have high performance. The ``ImmutableBitmapDataProvider`` does not provide the necessary data structure access.

A better solution is to simply cast the ``ImmutableBitmapDataProvider`` to its actual class (e.g., RoaringBitmap) as needed.
