### ISSUE TITLE
RoaringBitmap.or(RoaringBitmap) has side effect on argument

### ISSUE THREAD

**Issue by fathzer** [lemire/RoaringBitmap#60]
Hello,
In the JUnit test below, r1 is modified after been passed as an argument to or method (tested on 0.5.13):

	import static org.junit.Assert.*;
	import org.junit.Test;
	import org.roaringbitmap.RoaringBitmap;
	public class OrBugTest {
		@Test
		public void test() {
			RoaringBitmap r1 = new RoaringBitmap();
			// Strange thing: Replace this line by r1.add(131000) and the bug vanishes!
			r1.flip(131000, 131001);
			RoaringBitmap r2 = new RoaringBitmap();
			r2.add(220000);
			RoaringBitmap r3 = new RoaringBitmap();
			int killingPosition = 66000;
			r3.add(killingPosition);
		
			assertFalse(r1.contains(killingPosition)); //ok
			r2.or(r1);
			assertFalse(r1.contains(killingPosition)); //ok
			r2.or(r3);
			assertFalse(r1.contains(killingPosition)); //ko
		}
	}
Best regards,
Jean-Marc Astesana

**Comment by lemire** [comment]
Thank you Jean-Marc. This seems to indicate a possible bug with the ``flip`` function.

**Comment by lemire** [comment]
The fix is in git. Will be issuing a release shortly.

**Comment by lemire** [comment]
Please upgrade to 0.5.14.

**Comment by fathzer** [comment]
Hi,
Many thanks for fixing it so fast.
Merry christmas :-)
Jean-Marc
