### ISSUE TITLE
Request to add nextSetBit and nextClearBit perhaps other BitSet APIs

### ISSUE THREAD

**Issue by jimidle** [lemire/RoaringBitmap#9]
As obviously useful as this work is, it would be very much easier to move to if the API provided direct replacements for the standard Java `BitSet` API, even if in some cases they came perhaps with a performance warning.

While I implemented `nextSetBit` and `nextClearBit` trivially outside the package, it is probably done more efficiently within the package code I suspect (no time to look in to it I am afraid). All I did in external code is:

```java
    final static int nextClearBit(RoaringBitmap rbm, int b) {

        while (rbm.contains(b)) {
            b++;
        }
        return b;
    }

    final static int nextSetBit(RoaringBitmap rbm, int b) {

        if (rbm.contains(b)) {
            return b;  // The bit we were given is set
        }

        for (final int i : rbm) {

            if (i > b) {
                return i;
            }
        }
        return -1; // There are no set bits including or after the one given
    }
```

It does not matter to me that the API method names are slightly different but it might to others. Initially I was going to extend the `RoaringBitmap` class, but you have made it final so that cannot be done. So creating a wrapper to replace `BitSet` is not possible without creating a class the delegates to RoaringBitMap - just a thought that you might remove the `final`?

Thanks for publishing this.

**Comment by lemire** [comment]
@jimidle 

I should explain why this iteration approach has not been implemented. Thought it is entirely doable technically, as you have shown, the performance is likely to be unacceptably poor in general.  Leaving aside performance issues, it is not clear why this is any more convenient than an IntIterator *except* for use as a drop-in replacement for BitSet. But Java engineers probably came up with this non-standard iterator pattern for performance reasons... it is a performance trick that backfires for us. In general, having a drop-in replacement for BitSet with much poorer performance does not sound very appealing. Moreover, it is possible for someone to implement it using a wrapper if one must... in cases where performance is not an issue. In fact, someone could publish such a wrapper... it does not need to be part of the main library. (Or it could be added as an extra class if someone wants to contribute it.)

All in all, this tells me that we should close this issue as it is stated.

However, there is obvious merit in supporting the same functions as BitSet so I have created a new issue:

https://github.com/lemire/RoaringBitmap/issues/21


I am closing this issue.

Please re-open if you disagree.
